### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by jzoric** [VisualVest-GmbH/cnv-docs#1]
Hi,

Can you provide a simple getting started docs on how to run the basic setup?

**Comment by linoestevao** [comment]
@jzoric it's a work in progress

**Comment by linoestevao** [comment]
Hey @jzoric we are glad to announce the updated section in how to get started with docker-compose. [have a look](https://github.com/VisualVest-GmbH/cnv-docs#in-a-rush) or directly [Deploy on production with docker-compose](https://github.com/VisualVest-GmbH/cnv-docs#deploy-on-production-with-docker-compose)

**Comment by linoestevao** [comment]
@jzoric you can also find an integration example on a website at the bottom of the documentation:  [here](https://github.com/VisualVest-GmbH/cnv-docs#integrate-into-your-website)

**Comment by jovicazoric** [comment]
Thank you @linoestevao I'll check it today evening and get back to you.

**Comment by jzoric** [comment]
Thank you @linoestevao I'll check it today evening and get back to you.

**Comment by jzoric** [comment]
@linoestevao Thanks for updating the docs! 

Great, docker-compose works! 

Regarding local development:
- Docs should remove "build cnv-plugins" part because you can't build that project
- No default flow so App shows an error. Will there be a dummy flow for the local development to avoid the errors?

Regarding integration:
- What projects I need to build for "prod"? 
- index.html example shows error, it looks like localhost is not configured properly?

**Comment by linoestevao** [comment]
@jzoric what is the error on the index.html example?

You can use the flow in docker/config/nodered/flows.json as a starting point, we will add this on the docs as well

**Comment by linoestevao** [comment]
Within the docker-compose example, there is a server (cnv-react-app). This server will serve both /app/chat{.css,.js} and you should be able to run the example index.html with python or http-server.

If you've built the cnv-react-app, you have to make it public with eg.: nginx or the provided dockerfile on the same repo.

Let me know

**Comment by jzoric** [comment]
Thanks for the info. Will try it in the next days... in the meantime I hope the docs will be more clear on this.

**Comment by jzoric** [comment]
Done. For other issues use https://github.com/conversionplatform
